<div class="alert alert-success">
<h2> Комментарий наставника</h2>

Привет! Спасибо, что прислала задание:) Меня зовут Слепцов Артем и я буду проверять твой проект) Ты проделала большую работу над проектом, однако его еще можно улучшить. Извини за задержку при проверке(

Мои комментарии обозначены пометкой **Комментарий наставника**. Далее в файле ты сможешь найти их в похожих ячейках (если фон комментария <font color=green>зелёный</font> - всё сделано правильно; <font color=orange>оранжевый</font> - есть замечания, но не критично, воспринимай их в качестве рекомендаций; <font color=red>красный</font> - нужно переделать). Не удаляй эти комментарии и постарайся учесть их в ходе выполнения данного проекта. 

</div>

# Определение перспективного тарифа для телеком компании
<br>

## Описание проекта

Вы аналитик компании «Мегалайн» — федерального оператора сотовой связи. Клиентам предлагают два тарифных плана: «Смарт» и «Ультра». Чтобы скорректировать рекламный бюджет, коммерческий департамент хочет понять, какой тариф приносит больше денег.
<br>
Вам предстоит сделать предварительный анализ тарифов на небольшой выборке клиентов. В вашем распоряжении данные 500 пользователей «Мегалайна»: кто они, откуда, каким тарифом пользуются, сколько звонков и сообщений каждый отправил за 2018 год. Нужно проанализировать поведение клиентов и сделать вывод — какой тариф лучше.

### Описание тарифов
#### Тариф «Смарт»
* Ежемесячная плата: 550 рублей
* Включено 500 минут разговора, 50 сообщений и 15 Гб интернет-трафика
* Стоимость услуг сверх тарифного пакета:
* 		минута разговора: 3 рубля
* 		сообщение: 3 рубля
* 		1 Гб интернет-трафика: 200 рублей

#### Тариф «Ультра»
* Ежемесячная плата: 1950 рублей
* Включено 3000 минут разговора, 1000 сообщений и 30 Гб интернет-трафика
* Стоимость услуг сверх тарифного пакета:
* 		минута разговора: 1 рубль
* 		сообщение: 1 рубль
* 		1 Гб интернет-трафика: 150 рублей

<b>Обратите внимание</b>: «Мегалайн» всегда округляет вверх значения минут и мегабайтов. Если пользователь проговорил всего 1 секунду, в тарифе засчитывается целая минута.

### Краткий план работы:

#### Шаг 1. Откройте файл с данными и изучите общую информацию
#### Шаг 2. Подготовьте данные
* Приведите данные к нужным типам;
* Найдите и исправьте ошибки в данных.
Посчитайте для каждого пользователя:
* Количество сделанных звонков и израсходованных минут разговора по месяцам;
* Количество отправленных сообщений по месяцам;
* Объем израсходованного интернет-трафика по месяцам;
* Помесячную выручку с каждого пользователя (вычтите бесплатный лимит из суммарного количества звонков, сообщений и интернет-трафика; остаток умножьте на значение из тарифного плана; прибавьте абонентскую плату, соответствующую тарифному плану).
#### Шаг 3. Проанализируйте данные
* Опишите поведение клиентов оператора, исходя из выборки. 
* Сколько минут разговора, сколько сообщений и какой объём интернет-трафика требуется пользователям каждого тарифа в месяц? 
* Посчитайте среднее количество, дисперсию и стандартное отклонение. 
* Постройте гистограммы. 
* Опишите распределения.
#### Шаг 4. Проверьте гипотезы
* Средняя выручка пользователей тарифов «Ультра» и «Смарт» различается;
* Средняя выручка пользователей из Москвы отличается от выручки пользователей из других регионов;
#### Шаг 5. Напишите общий вывод


### Описание данных

#### Таблица users (информация о пользователях):
* 		*user_id* — уникальный идентификатор пользователя
* 		*first_name* — имя пользователя
* 		*last_name* — фамилия пользователя
* 		*age* — возраст пользователя (годы)
* 		*reg_date* — дата подключения тарифа (день, месяц, год)
* 		*churn_date* — дата прекращения пользования тарифом (если значение пропущено, то тариф ещё действовал на момент выгрузки данных)
* 		*city* — город проживания пользователя
* 		*tariff* — название тарифного плана

#### Таблица calls (информация о звонках):
* 		*id* — уникальный номер звонка
* 		*call_date* — дата звонка
* 		*duration* — длительность звонка в минутах
* 		*user_id* — идентификатор пользователя, сделавшего звонок

#### Таблица messages (информация о сообщениях):
* 		*id* — уникальный номер сообщения
* 		*message_date* — дата сообщения
* 		*user_id* — идентификатор пользователя, отправившего сообщение

#### Таблица internet (информация об интернет-сессиях):
* 		*id* — уникальный номер сессии
* 		*mb_used* — объём потраченного за сессию интернет-трафика (в мегабайтах)
* 		*session_date* — дата интернет-сессии
* 		*user_id* — идентификатор пользователя

#### Таблица tariffs (информация о тарифах):
* 		*tariff_name* — название тарифа
* 		*rub_monthly_fee* — ежемесячная абонентская плата в рублях
* 		*minutes_included* — количество минут разговора в месяц, включённых в абонентскую плату
* 		*messages_included* — количество сообщений в месяц, включённых в абонентскую плату
* 		*mb_per_month_included* — объём интернет-трафика, включённого в абонентскую плату (в мегабайтах)
* 		*rub_per_minute* — стоимость минуты разговора сверх тарифного пакета (например, если в тарифе 100 минут разговора в месяц, то со 101 минуты будет взиматься плата)
* 		*rub_per_message* — стоимость отправки сообщения сверх тарифного пакета
* 		*rub_per_gb* — стоимость дополнительного гигабайта интернет-трафика сверх тарифного пакета (1 гигабайт = 1024 мегабайта)


<div class="alert alert-success">
<h2> Комментарий наставника</h2>

Вступление в работу очень важно. Так ты поясняешь то, чему она посвящена.

</div>

## Шаг 1. Откройте файл с данными и изучите общую информацию

In [5]:
#Импортируем все необходимые библиотеки
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpt
import seaborn as sns
from termcolor import colored
from scipy import stats as st
import numpy as np

In [6]:
#Определяем болд
def bold(): 
    return "\033[1m"

def bold_end(): 
    return "\033[0m"

#Ставим формат для нумериков
pd.options.display.float_format = '{: >10.2f}'.format

In [7]:
#Достаем файлы
df_calls = pd.read_csv('datasets/calls.csv', sep=',',decimal='.')
df_internet = pd.read_csv('datasets/internet.csv', sep=',',decimal='.', index_col=0)
df_messages = pd.read_csv('datasets/messages.csv', sep=',',decimal='.')
df_tariffs = pd.read_csv('datasets/tariffs.csv', sep=',',decimal='.')
df_users = pd.read_csv('datasets/users.csv', sep=',',decimal='.')

___Сделаем функцию___


Функция print_basic_info, для вывода информации о массиве, и его переменных.

4 входных параметра

* *base* - название базы данных
* *info* - 1: вывод информации о массиве, другое: не вывод
* *head* - n: вывод примера базы (вывод n - строк), n < 1: не вывод
* *describe* - 1: вывод описания переменных массива, другое: не вывод

In [8]:
def print_basic_info(base, info, head, describe):
    if info == 1:
        print(bold(), colored('info','green'), bold_end(), "\n")
        print( base.info())  
    if head >= 1:
        print(bold(),colored('head','green'),bold_end(),"\n")
        display(base.head(head))
    if describe == 1:
        for i in base.columns:
            print(bold(), colored(i,'blue'),bold_end(), "\n", base[i].unique())

<div class="alert alert-success">
<h2> Комментарий наставника</h2>

Описание функции часто вставляется в саму функцию. Однако и так вполне хорошо.  

</div>

___Смотрим файлы отдельно___

___Таблица calls (информация о звонках):___

In [9]:
#Инфо
print_basic_info(df_calls,1,3,0)

 info  

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202607 entries, 0 to 202606
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype  
---  ------     --------------   -----  
 0   id         202607 non-null  object 
 1   call_date  202607 non-null  object 
 2   duration   202607 non-null  float64
 3   user_id    202607 non-null  int64  
dtypes: float64(1), int64(1), object(2)
memory usage: 6.2+ MB
None
 head  



id   call_date   duration  user_id
0  1000_0  2018-07-25       0.00     1000
1  1000_1  2018-08-17       0.00     1000
2  1000_2  2018-06-11       2.85     1000

<div class="alert alert-warning">
<h2> Комментарий наставника</h2>

Таблицы на печать выводи с помощью метода display. print переводит данные в строку, а нам этого не надо. 

</div>

___Вывод:___

Всего 202607 кейсов. Пропусков в заполнении нет. <br>
Есть повторы в user_id - клиент сделал несколько звонков.<br>
user_id по факту объект, а не инт. Необходимо поправить. Но скорее уже в финальном массиве.<br>
call_date - Дата интеракции. Нужно привести к формату даты и выделить месяц. И проверить, что год только 2018.

#### План предобработки по массиву:
* Сначала надо убрать пустые.
* Округлить до минут звонки __!вверх__
* Посчитать сумму минут за месяц
* Посчитать количество за месяц
* Подгрузить к таблице users

___Таблица internet (информация об интернет-сессиях):___

In [10]:
#Инфо
print_basic_info(df_internet,1,3,0)

 info  

<class 'pandas.core.frame.DataFrame'>
Int64Index: 149396 entries, 0 to 149395
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   id            149396 non-null  object 
 1   mb_used       149396 non-null  float64
 2   session_date  149396 non-null  object 
 3   user_id       149396 non-null  int64  
dtypes: float64(1), int64(1), object(2)
memory usage: 5.7+ MB
None
 head  



id    mb_used session_date  user_id
0  1000_0     112.95   2018-11-25     1000
1  1000_1    1052.81   2018-09-07     1000
2  1000_2    1197.26   2018-06-25     1000

<div class="alert alert-warning">
<h2> Комментарий наставника</h2>

Задав параметр index_col=0 метода read_csv, мы можем сделать данный столбец 'Unnamed: 0' индексом, коим он и является. 

</div>

___Вывод :___

Всего 149396 кейсов. Пропусков в заполнении нет. <br>
Есть повторы в user_id - клиент заходил в интернет несколько раз.<br>
user_id по факту обьект, а не инт. Необходимо поправить. Но скорее уже в финальном массиве.<br>
call_date - Дата интеракции. Нужно привести к формату даты и выделить месяц. И проверить, что год только 2018<br>

#### План предобработки по массиву:
* Округлить до мегабайт !вверх
* Посчитать сумму мегабайт за месяц
* Посчитать количество заходов за месяц
* Подгрузить к таблице users

___Таблица messages (информация о сообщениях):___

In [11]:
#Инфо
print_basic_info(df_messages,1,3,0)

 info  

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123036 entries, 0 to 123035
Data columns (total 3 columns):
 #   Column        Non-Null Count   Dtype 
---  ------        --------------   ----- 
 0   id            123036 non-null  object
 1   message_date  123036 non-null  object
 2   user_id       123036 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 2.8+ MB
None
 head  



id message_date  user_id
0  1000_0   2018-06-27     1000
1  1000_1   2018-10-08     1000
2  1000_2   2018-08-04     1000

___Вывод :___

Всего 123036 кейсов. Пропусков в заполнении нет. <br>
Есть повторы в user_id - клиент высылал несколько сообщений.<br>
user_id по факту объект, а не инт. Необходимо поправить. Но скорее уже в финальном массиве.<br>
call_date - Дата интеракции. Нужно привести к формату даты и выделить месяц. И проверить, что год только 2018<br>

#### План предобработки по массиву:
* Посчитать количество смс за месяц
* Подгрузить к таблице users

___Таблица tariffs (информация о тарифах):___

In [12]:
#Инфо
print_basic_info(df_tariffs,1,3,0)

 info  

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   messages_included      2 non-null      int64 
 1   mb_per_month_included  2 non-null      int64 
 2   minutes_included       2 non-null      int64 
 3   rub_monthly_fee        2 non-null      int64 
 4   rub_per_gb             2 non-null      int64 
 5   rub_per_message        2 non-null      int64 
 6   rub_per_minute         2 non-null      int64 
 7   tariff_name            2 non-null      object
dtypes: int64(7), object(1)
memory usage: 256.0+ bytes
None
 head  



messages_included  mb_per_month_included  minutes_included  \
0                 50                  15360               500   
1               1000                  30720              3000   

   rub_monthly_fee  rub_per_gb  rub_per_message  rub_per_minute tariff_name  
0              550         200                3               3       smart  
1             1950         150                1               1       ultra

___Вывод :___

Всего 2 кейса. По факту словарь c информацией о тарифах <br>

#### План предобработки по массиву:
* Сверить информацию в таблице с описанием тарифа 
* Подгрузить к таблице users на основе названия тарифа

___Таблица users (информация о пользователях):___

In [13]:
#Инфо:
print_basic_info(df_users,1,3,0)

 info  

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   user_id     500 non-null    int64 
 1   age         500 non-null    int64 
 2   churn_date  38 non-null     object
 3   city        500 non-null    object
 4   first_name  500 non-null    object
 5   last_name   500 non-null    object
 6   reg_date    500 non-null    object
 7   tariff      500 non-null    object
dtypes: int64(2), object(6)
memory usage: 31.4+ KB
None
 head  



user_id  age churn_date         city first_name  last_name    reg_date  \
0     1000   52        NaN    Краснодар     Рафаил  Верещагин  2018-05-25   
1     1001   41        NaN       Москва       Иван       Ежов  2018-11-01   
2     1002   59        NaN  Стерлитамак    Евгений  Абрамович  2018-06-17   

  tariff  
0  ultra  
1  smart  
2  smart

___Вывод :___

Всего 500 кейсов. <br>
Есть пропуски в переменной churn_date (дата прекращения пользования тарифом). Однако есть пометка, что если значение пропущено, то тариф ещё действовал на момент выгрузки данных <br>
user_id по факту объект, а не инт. Необходимо поправить.<br>
reg_date и churn_date - дата подключения тарифа и дата прекращения пользования тарифом. Нужно привести к формату даты.<br>

#### План предобработки по массиву:
* user_id - проверить на уникальность
* user_id - перевести в формат объект
* reg_date - перевести в формат даты

После чего база будет готова к подгрузке информации о смс, интернете, телефонных звонках и описания тарифа.<br>
Далее сможем рассчитать необходимые доп. переменные:
* 		количество сделанных звонков и израсходованных минут разговора по месяцам;
* 		количество отправленных сообщений по месяцам;
* 		объем израсходованного интернет-трафика по месяцам;
* 		помесячную выручку с каждого пользователя 


<div class="alert alert-success">
<h2> Комментарий наставника</h2>

Подумай также о возможных причинах появления ошибок в данных, а также о том, являются ли они случайными или нет. Можно высказать предварительные варианты их обработки. 

Первый взгляд на таблицы выполнен. Здорово, что по каждому параметру приведен план дальнейших действий. 

</div>

## Шаг 2. Подготовьте данные

#### Делаем функции (для удобства)

Функция ____ft_namecount___, для вывода названия переменной, частотной нормированной таблицы и описания переменной.

5 входных параметров

* base - название базы данных
* index - название переменной в базе
* table - 1: вывод частотной нормированной таблицы, 0: не вывод
* sort - 1: сортировка таблицы по лейблам переменной, 0: не сортировка
* describe - 1: вывод описания переменной, 0: не вывод

In [14]:
def ft_name_count (base, name , table, sort, describe):
    print(bold(), colored(name,'blue') , bold_end(), "\n")
    if table != 0:
        s = (base[name].value_counts(normalize=True))
        if sort != 0:
            s.sort_index(inplace=True)
        print(s)
    if describe != 0:
        print(base[name].describe())

Работать будет с базами последовательно.

Начнем с проверки "основной" базы, чтобы потом к ней спокойно подливать информацию из других.
### Таблица users (информация о пользователях):

* *Приводим данные к нужным типам*
* *Находим и исправляем ошибки в данных*

*Приводим данные к нужным типам*


In [15]:
# Обьект
df_users['user_id'] = df_users[
    'user_id'].astype('object')

# Дата
df_users['churn_date'] = pd.to_datetime(df_users[
    'churn_date'], format='%Y-%m-%d')
df_users['reg_date'] = pd.to_datetime(df_users[
    'reg_date'], format='%Y-%m-%d')

# Сразу выделим месяц и год подключения и отключения
df_users['reg_year'] = df_users['reg_date'].dt.year
df_users['reg_month'] = df_users['reg_date'].dt.month

df_users['churn_year'] = df_users['churn_date'].dt.year
df_users['churn_month'] = df_users['churn_date'].dt.month

# Проверяем
print_basic_info(df_users,1,3,0)

 info  

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype         
---  ------       --------------  -----         
 0   user_id      500 non-null    object        
 1   age          500 non-null    int64         
 2   churn_date   38 non-null     datetime64[ns]
 3   city         500 non-null    object        
 4   first_name   500 non-null    object        
 5   last_name    500 non-null    object        
 6   reg_date     500 non-null    datetime64[ns]
 7   tariff       500 non-null    object        
 8   reg_year     500 non-null    int64         
 9   reg_month    500 non-null    int64         
 10  churn_year   38 non-null     float64       
 11  churn_month  38 non-null     float64       
dtypes: datetime64[ns](2), float64(2), int64(3), object(5)
memory usage: 47.0+ KB
None
 head  



user_id  age churn_date         city first_name  last_name   reg_date  \
0    1000   52        NaT    Краснодар     Рафаил  Верещагин 2018-05-25   
1    1001   41        NaT       Москва       Иван       Ежов 2018-11-01   
2    1002   59        NaT  Стерлитамак    Евгений  Абрамович 2018-06-17   

  tariff  reg_year  reg_month  churn_year  churn_month  
0  ultra      2018          5         nan          nan  
1  smart      2018         11         nan          nan  
2  smart      2018          6         nan          nan

*Находим и исправляем ошибки в данных*

___user_id — уникальный идентификатор пользователя___

In [16]:
ft_name_count(df_users,"user_id", 0,0,1)
#все значения уникальны! прекрасно!

 user_id  

count      500
unique     500
top       1023
freq         1
Name: user_id, dtype: int64


Имя и фамилия имеют быть право какими угодно. Проверять не будем.

смотрим ___Возраст___

In [17]:
ft_name_count(df_users,"age", 0,0,1)
#Возраст с 18 лет! Выбросов нет! Хорошо!

 age  

count       500.00
mean         46.59
std          16.67
min          18.00
25%          32.00
50%          46.00
75%          62.00
max          75.00
Name: age, dtype: float64


___дата подключения тарифа и дата прекращения пользования тарифом___

___смотрим новые переменные (reg_year, reg_month, churn_year, churn_month)___

In [18]:
ft_name_count(df_users,"reg_year", 1,1,0)
ft_name_count(df_users,"reg_month", 1,1,0)

ft_name_count(df_users,"churn_year", 1,1,0)
ft_name_count(df_users,"churn_month", 1,1,0)

#Странных значений нет. хорошо

 reg_year  

2018         1.00
Name: reg_year, dtype: float64
 reg_month  

1          0.09
2          0.08
3          0.06
4          0.11
5          0.08
6          0.08
7          0.09
8          0.10
9          0.07
10         0.09
11         0.08
12         0.07
Name: reg_month, dtype: float64
 churn_year  

2018.00         1.00
Name: churn_year, dtype: float64
 churn_month  

 8.00         0.05
 9.00         0.08
10.00         0.24
11.00         0.21
12.00         0.42
Name: churn_month, dtype: float64


___city___

In [19]:
ft_name_count(df_users,"city", 1,0,0)

#переменная нормальная, написание непобилось. Больше всего МСК и СПБ.

 city  

Москва                  0.20
Санкт-Петербург         0.08
Новосибирск             0.03
Казань                  0.03
Омск                    0.03
                     ...    
Иваново                 0.00
Архангельск             0.00
Химки                   0.00
Подольск                0.00
Нижневартовск           0.00
Name: city, Length: 76, dtype: float64


___tariff___

In [20]:
ft_name_count(df_users,"tariff", 1,0,0)

#лишних тарифов нет

 tariff  

smart         0.70
ultra         0.30
Name: tariff, dtype: float64


___Вывод:___

Изменили типы данных где это необходимо. Выделили доп. переменные из дат.

Обратила внимание, что данные подключения и отключения от тарифа также только за 2018 год. Клиенты на тарифах недавно (относительно данных звонков и смс).

Дублей в уникальном номере респондента нет.
Возраст только с 18 лет.
Лишних тарифов нет.

Данные чистые. Необходимости в исправлении данных нет.

<div class="alert alert-success">
<h2> Комментарий наставника</h2>

Дата теперь представлена в формате даты. В остальном данная таблице была в порядке. 

</div>

Далее смотрим таблицу:
### Таблица calls (информация о звонках):

* *Приводим данные к нужным типам*
* *Находим и исправляем ошибки в данных*
* *Рассчитываем количество сделанных звонков и израсходованных минут разговора по месяцам*
* *Добавляем информацию в массив df_users*

*Приводим данные к нужным типам*

In [21]:
# Обьект
df_calls['user_id'] = df_calls['user_id'].astype('object')

# Дата
df_calls['call_date'] = pd.to_datetime(df_calls[
    'call_date'], format='%Y-%m-%d')

# Сразу выделим месяц и год
df_calls['call_year'] = df_calls['call_date'].dt.year
df_calls['call_month'] = df_calls['call_date'].dt.month

# Проверяем
print_basic_info(df_calls,1,3,0)

 info  

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202607 entries, 0 to 202606
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype         
---  ------      --------------   -----         
 0   id          202607 non-null  object        
 1   call_date   202607 non-null  datetime64[ns]
 2   duration    202607 non-null  float64       
 3   user_id     202607 non-null  object        
 4   call_year   202607 non-null  int64         
 5   call_month  202607 non-null  int64         
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 9.3+ MB
None
 head  



id  call_date   duration user_id  call_year  call_month
0  1000_0 2018-07-25       0.00    1000       2018           7
1  1000_1 2018-08-17       0.00    1000       2018           8
2  1000_2 2018-06-11       2.85    1000       2018           6

*Находим и исправляем ошибки в данных*

___id — уникальный номер звонка___

In [22]:
ft_name_count(df_calls,"id", 0,0,1)

#Все уникальные - отлично!

 id  

count       202607
unique      202607
top       1300_481
freq             1
Name: id, dtype: object


___дата звонка___
___будем смотреть переменные call_year и call_month___

In [23]:
ft_name_count(df_calls,"call_year", 1,0,0)
ft_name_count(df_calls,"call_month", 1,1,0)

#только 2018 - отлично! Месяцы есть все - огонь! 
#Понятно, что первых месяцев меньше. Многие еше не подключились к тарифу

 call_year  

2018         1.00
Name: call_year, dtype: float64
 call_month  

1          0.01
2          0.02
3          0.03
4          0.05
5          0.06
6          0.07
7          0.09
8          0.11
9          0.12
10         0.13
11         0.15
12         0.17
Name: call_month, dtype: float64


___duration___

In [24]:
ft_name_count(df_calls,"duration", 0,0,1)

 duration  

count    202607.00
mean          6.76
std           5.84
min           0.00
25%           1.30
50%           6.00
75%          10.70
max          38.00
Name: duration, dtype: float64


Есть нули - не отвеченные звоники -  за них человек не платит изначит при оценке тарифа они не нужны.

* *Уберем нули*

В тарифе при подсчете секунды округялются вверх до минут

* *Округлим вверх до минут*

<div class="alert alert-success">
<h2> Комментарий наставника</h2>

Исходя из описанной гипотезы звонки с нулевой длительностью обработаны правильным образом.

</div>

In [25]:
#Убираем нули
df_calls = df_calls.query('duration != 0')

#проверяем
ft_name_count(df_calls,"duration", 0,0,1)

 duration  

count    162994.00
mean          8.40
std           5.35
min           0.01
25%           4.17
50%           7.74
75%          11.85
max          38.00
Name: duration, dtype: float64


<div class="alert alert-success">
<h2> Комментарий наставника</h2>

Верно, что округление производится до суммирования. Это согласуется с тем, как оператор фиксирует выручку.

</div>

In [26]:
#Округлим вверх до минут
df_calls['duration'] = np.ceil(df_calls['duration'])

#проверяем
ft_name_count(df_calls,"duration", 0,0,1)

 duration  

count    162994.00
mean          8.90
std           5.35
min           1.00
25%           5.00
50%           8.00
75%          12.00
max          38.00
Name: duration, dtype: float64


___user_id___

In [27]:
ft_name_count(df_calls,"user_id", 0,0,1)

#должно быть не более 500 уникальных юзер ID. Так и есть

 user_id  

count     162994
unique       492
top         1377
freq        1424
Name: user_id, dtype: int64


___Вывод:___

Изменили типы данных где это необходимо. * Выделили доп. переменные из дат.

Дублей в уникальном номере звонка нет.

Как и обещали - звонки только с 2018 год. 
В первые месяцы года звонков меньше т.к. у нас выборка подключившихся за 18 год, а многие еще не подключились к тарифу.

492 уникальных номеров юзеров значит почти все пользовались звонками.

**Корректировка**

___duration___

* Найдены нулевые значения (неотвеченные звонки). Удалили кейсы с ними. За них человек не платит и значит при оценке тарифа они не нужны.
* При подсчете секунды в тарифе идет округление вверх до минут. Округлили в базе аналогично.

*Рассчитываем количество сделанных звонков и израсходованных минут разговора по месяцам*


In [28]:
# считаем
table_id_calls = df_calls.pivot_table(index=['user_id'], 
                                     columns='call_month',
                                     values='duration', 
                                     aggfunc=['sum','count']
                                    )

table_id_calls = table_id_calls.reset_index()

table_id_calls.head(2)

user_id        sum                                              \
call_month                  1          2          3          4          5   
0             1000        nan        nan        nan        nan     159.00   
1             1001        nan        nan        nan        nan        nan   

                                                        ...      count  \
call_month          6          7          8          9  ...          3   
0              172.00     340.00     408.00     466.00  ...        nan   
1                 nan        nan        nan        nan  ...        nan   

                                                                              \
call_month          4          5          6          7          8          9   
0                 nan      17.00      28.00      41.00      42.00      46.00   
1                 nan        nan        nan        nan        nan        nan   

                                             
call_month         10         11         12  
0               44.00      37.00      38.00  
1                 nan      45.00      47.00  

[2 rows x 25 columns]

In [29]:
#сделаем нормальые названия

table_id_calls.columns = ['user_id',
                              'calls_min_month_1','calls_min_month_2',
                              'calls_min_month_3','calls_min_month_4',
                              'calls_min_month_5','calls_min_month_6',
                              'calls_min_month_7','calls_min_month_8',
                              'calls_min_month_9','calls_min_month_10',
                              'calls_min_month_11','calls_min_month_12',
                              'calls_count_month_1','calls_count_month_2',
                              'calls_count_month_3','calls_count_month_4',
                              'calls_count_month_5','calls_count_month_6',
                              'calls_count_month_7','calls_count_month_8',
                              'calls_count_month_9','calls_count_month_10',
                              'calls_count_month_11','calls_count_month_12',
                             ]

table_id_calls = table_id_calls.set_index('user_id')

table_id_calls.head(2)

calls_min_month_1  calls_min_month_2  calls_min_month_3  \
user_id                                                            
1000                   nan                nan                nan   
1001                   nan                nan                nan   

         calls_min_month_4  calls_min_month_5  calls_min_month_6  \
user_id                                                            
1000                   nan             159.00             172.00   
1001                   nan                nan                nan   

         calls_min_month_7  calls_min_month_8  calls_min_month_9  \
user_id                                                            
1000                340.00             408.00             466.00   
1001                   nan                nan                nan   

         calls_min_month_10  ...  calls_count_month_3  calls_count_month_4  \
user_id                      ...                                             
1000                 350.00  ...                  nan                  nan   
1001                    nan  ...                  nan                  nan   

         calls_count_month_5  calls_count_month_6  calls_count_month_7  \
user_id                                                                  
1000                   17.00                28.00                41.00   
1001                     nan                  nan                  nan   

         calls_count_month_8  calls_count_month_9  calls_count_month_10  \
user_id                                                                   
1000                   42.00                46.00                 44.00   
1001                     nan                  nan                   nan   

         calls_count_month_11  calls_count_month_12  
user_id                                              
1000                    37.00                 38.00  
1001                    45.00                 47.00  

[2 rows x 24 columns]


*Добавляем информацию в массив df_users*

In [30]:
df_users_join = df_users.join(table_id_calls, on='user_id')

#проверяем
print(df_users_join.info(2))
df_users_join.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 36 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   user_id               500 non-null    object        
 1   age                   500 non-null    int64         
 2   churn_date            38 non-null     datetime64[ns]
 3   city                  500 non-null    object        
 4   first_name            500 non-null    object        
 5   last_name             500 non-null    object        
 6   reg_date              500 non-null    datetime64[ns]
 7   tariff                500 non-null    object        
 8   reg_year              500 non-null    int64         
 9   reg_month             500 non-null    int64         
 10  churn_year            38 non-null     float64       
 11  churn_month           38 non-null     float64       
 12  calls_min_month_1     42 non-null     float64       
 13  calls_min_month_2   

user_id  age churn_date       city first_name  last_name   reg_date tariff  \
0    1000   52        NaT  Краснодар     Рафаил  Верещагин 2018-05-25  ultra   
1    1001   41        NaT     Москва       Иван       Ежов 2018-11-01  smart   

   reg_year  reg_month  ...  calls_count_month_3  calls_count_month_4  \
0      2018          5  ...                  nan                  nan   
1      2018         11  ...                  nan                  nan   

   calls_count_month_5  calls_count_month_6  calls_count_month_7  \
0                17.00                28.00                41.00   
1                  nan                  nan                  nan   

   calls_count_month_8  calls_count_month_9  calls_count_month_10  \
0                42.00                46.00                 44.00   
1                  nan                  nan                   nan   

   calls_count_month_11  calls_count_month_12  
0                 37.00                 38.00  
1                 45.00                 47.00  

[2 rows x 36 columns]

``` Альтернативная версия  ```

In [31]:
temp_df_users = df_users
df_users_join2 = pd.DataFrame()
i= 1
while i <= 12:
    temp_df_users['month'] = i
    df_users_join2 = df_users_join2.append(temp_df_users)
    i = i + 1

#месяцы
print(df_users_join2.info(), df_users_join2['month'].unique())

#df_users_join2['month_id'] = str(df_users_join2['month']) + df_users_join2['user_id']
df_users_join2 = df_users_join2.set_index(['month','user_id']) 



df_users_join2.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6000 entries, 0 to 499
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype         
---  ------       --------------  -----         
 0   user_id      6000 non-null   object        
 1   age          6000 non-null   int64         
 2   churn_date   456 non-null    datetime64[ns]
 3   city         6000 non-null   object        
 4   first_name   6000 non-null   object        
 5   last_name    6000 non-null   object        
 6   reg_date     6000 non-null   datetime64[ns]
 7   tariff       6000 non-null   object        
 8   reg_year     6000 non-null   int64         
 9   reg_month    6000 non-null   int64         
 10  churn_year   456 non-null    float64       
 11  churn_month  456 non-null    float64       
 12  month        6000 non-null   int64         
dtypes: datetime64[ns](2), float64(2), int64(4), object(5)
memory usage: 656.2+ KB
None [ 1  2  3  4  5  6  7  8  9 10 11 12]


age churn_date         city first_name  last_name   reg_date  \
month user_id                                                                 
1     1000      52        NaT    Краснодар     Рафаил  Верещагин 2018-05-25   
      1001      41        NaT       Москва       Иван       Ежов 2018-11-01   
      1002      59        NaT  Стерлитамак    Евгений  Абрамович 2018-06-17   
      1003      23        NaT       Москва      Белла   Белякова 2018-08-17   
      1004      68        NaT  Новокузнецк    Татьяна   Авдеенко 2018-05-14   

              tariff  reg_year  reg_month  churn_year  churn_month  
month user_id                                                       
1     1000     ultra      2018          5         nan          nan  
      1001     smart      2018         11         nan          nan  
      1002     smart      2018          6         nan          nan  
      1003     ultra      2018          8         nan          nan  
      1004     ultra      2018          5         nan          nan

In [32]:
table_id_calls2 = df_calls.pivot_table(index=['call_month','user_id'], 
                                     values='duration', 
                                     aggfunc=['sum','count']
                                    )

table_id_calls2 = table_id_calls2.reset_index()
table_id_calls2.columns = ['month','user_id',
                              'duration_sum','duration_count']

table_id_calls2 = table_id_calls2.set_index(['month','user_id']) 

table_id_calls2.head(2)

duration_sum  duration_count
month user_id                              
1     1005            95.00              11
      1032           380.00              44

In [33]:
df_users_join2 = df_users_join2.join(table_id_calls2)

#проверяем
print(df_users_join2.info(2))
df_users_join2.head(2)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6000 entries, (1, 1000) to (12, 1499)
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   age             6000 non-null   int64         
 1   churn_date      456 non-null    datetime64[ns]
 2   city            6000 non-null   object        
 3   first_name      6000 non-null   object        
 4   last_name       6000 non-null   object        
 5   reg_date        6000 non-null   datetime64[ns]
 6   tariff          6000 non-null   object        
 7   reg_year        6000 non-null   int64         
 8   reg_month       6000 non-null   int64         
 9   churn_year      456 non-null    float64       
 10  churn_month     456 non-null    float64       
 11  duration_sum    3168 non-null   float64       
 12  duration_count  3168 non-null   float64       
dtypes: datetime64[ns](2), float64(4), int64(3), object(4)
memory usage: 791.1+ KB
None


age churn_date       city first_name  last_name   reg_date  \
month user_id                                                               
1     1000      52        NaT  Краснодар     Рафаил  Верещагин 2018-05-25   
      1001      41        NaT     Москва       Иван       Ежов 2018-11-01   

              tariff  reg_year  reg_month  churn_year  churn_month  \
month user_id                                                        
1     1000     ultra      2018          5         nan          nan   
      1001     smart      2018         11         nan          nan   

               duration_sum  duration_count  
month user_id                                
1     1000              nan             nan  
      1001              nan             nan

___Вывод:___

Сделали сводную таблицу, чтобы узнать для каждого айди сумму использованных минут и количество звонков в каждый месяц.

Дополнили этими данными базу клиентов.

<div class="alert alert-success">
<h2> Комментарий наставника</h2>

Лучше использовать несколько иную структуру таблицы. Месяца расположить в столбце и для каждого клиента рассчитывать потребление услуг в конкретном месяце. Так вся информация будет храниться в одной таблице, а еще она будет иметь более естественный вид. 

</div>

Смотрим на следующую базу
### Таблица messages (информация о сообщениях):

* *Приводим данные к нужным типам*
* *Находим и исправляем ошибки в данных*
* *Рассчитываем количество отправленных сообщений по месяцам*
* *Добавляем информацию в массив df_users_join*

*Приводим данные к нужным типам*

In [34]:
# Обьект
df_messages['user_id'] = df_messages['user_id'].astype('object')

# Дата
df_messages['message_date'] = pd.to_datetime(df_messages[
    'message_date'], format='%Y-%m-%d')

# Сразу выделим месяц и год 
df_messages['message_year'] = df_messages['message_date'].dt.year
df_messages['message_month'] = df_messages['message_date'].dt.month

# Проверяем
print_basic_info(df_messages,1,3,0)

 info  

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123036 entries, 0 to 123035
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype         
---  ------         --------------   -----         
 0   id             123036 non-null  object        
 1   message_date   123036 non-null  datetime64[ns]
 2   user_id        123036 non-null  object        
 3   message_year   123036 non-null  int64         
 4   message_month  123036 non-null  int64         
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 4.7+ MB
None
 head  



id message_date user_id  message_year  message_month
0  1000_0   2018-06-27    1000          2018              6
1  1000_1   2018-10-08    1000          2018             10
2  1000_2   2018-08-04    1000          2018              8

*Находим и исправляем ошибки в данных*

___id___

In [35]:
ft_name_count(df_messages,"id", 0,0,1)

#id уникальны. отлично

 id  

count       123036
unique      123036
top       1300_481
freq             1
Name: id, dtype: object


___дата сообщения___
___возьмем новые переменные message_year, message_month___

In [36]:
ft_name_count(df_messages,"message_year", 1,1,0)
ft_name_count(df_messages,"message_month", 1,1,0)

#Только 18 год и все месяцы есть. отлично.

 message_year  

2018         1.00
Name: message_year, dtype: float64
 message_month  

1          0.01
2          0.02
3          0.03
4          0.04
5          0.06
6          0.07
7          0.09
8          0.11
9          0.12
10         0.14
11         0.15
12         0.17
Name: message_month, dtype: float64


___user_id___

In [37]:
ft_name_count(df_messages,"user_id", 0,0,1)

#должно быть не более 500 уникальных юзер ID. Так и есть

 user_id  

count     123036
unique       426
top         1277
freq        1463
Name: user_id, dtype: int64


___Вывод:___

Изменили типы данных где это необходимо. Выделили доп. переменные из дат.

Дублей в уникальном номере сообщения нет.

Как и обещали -  только с 2018 год. 
В первые месяцы года звонков меньше т.к. у нас сообщений подключившихся за 18 год, а многие еще не подключились к тарифу.

426 уникальных номеров юзеров значит смс пользовались чуть меньше клиентов, чем звонками. Но все равно значительная часть (4 из 5).

Данные чистые. Необходимости в исправлении данных нет.




*Рассчитываем количество отправленных сообщений по месяцам*

In [38]:
# считаем
table_id_messages = df_messages.pivot_table(index=['user_id'], 
                                     columns='message_month',
                                     values='id', 
                                     aggfunc='count'
                                    )

table_id_messages = table_id_messages.reset_index()

table_id_messages.head(2)

message_month  user_id          1          2          3          4          5  \
0                 1000        nan        nan        nan        nan      22.00   
1                 1002        nan        nan        nan        nan        nan   

message_month          6          7          8          9         10  \
0                  60.00      75.00      81.00      57.00      73.00   
1                   4.00      11.00      13.00       4.00      10.00   

message_month         11         12  
0                  58.00      70.00  
1                  16.00      12.00

In [39]:
#сделаем нормальые названия

table_id_messages.columns = ['user_id',
                              'message_count_month_1','message_count_month_2',
                              'message_count_month_3','message_count_month_4',
                              'message_count_month_5','message_count_month_6',
                              'message_count_month_7','message_count_month_8',
                              'message_count_month_9','message_count_month_10',
                              'message_count_month_11','message_count_month_12',
                             ]

table_id_messages = table_id_messages.set_index('user_id')

table_id_messages.head(2)

message_count_month_1  message_count_month_2  message_count_month_3  \
user_id                                                                        
1000                       nan                    nan                    nan   
1002                       nan                    nan                    nan   

         message_count_month_4  message_count_month_5  message_count_month_6  \
user_id                                                                        
1000                       nan                  22.00                  60.00   
1002                       nan                    nan                   4.00   

         message_count_month_7  message_count_month_8  message_count_month_9  \
user_id                                                                        
1000                     75.00                  81.00                  57.00   
1002                     11.00                  13.00                   4.00   

         message_count_month_10  message_count_month_11  \
user_id                                                   
1000                      73.00                   58.00   
1002                      10.00                   16.00   

         message_count_month_12  
user_id                          
1000                      70.00  
1002                      12.00

*Добавляем информацию в массив df_users_join*

In [40]:
df_users_join = df_users_join.join(table_id_messages, on='user_id')

print(df_users_join.info(2))

df_users_join.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 48 columns):
 #   Column                  Non-Null Count  Dtype         
---  ------                  --------------  -----         
 0   user_id                 500 non-null    object        
 1   age                     500 non-null    int64         
 2   churn_date              38 non-null     datetime64[ns]
 3   city                    500 non-null    object        
 4   first_name              500 non-null    object        
 5   last_name               500 non-null    object        
 6   reg_date                500 non-null    datetime64[ns]
 7   tariff                  500 non-null    object        
 8   reg_year                500 non-null    int64         
 9   reg_month               500 non-null    int64         
 10  churn_year              38 non-null     float64       
 11  churn_month             38 non-null     float64       
 12  calls_min_month_1       42 non-null     float64   

user_id  age churn_date       city first_name  last_name   reg_date tariff  \
0    1000   52        NaT  Краснодар     Рафаил  Верещагин 2018-05-25  ultra   
1    1001   41        NaT     Москва       Иван       Ежов 2018-11-01  smart   

   reg_year  reg_month  ...  message_count_month_3  message_count_month_4  \
0      2018          5  ...                    nan                    nan   
1      2018         11  ...                    nan                    nan   

   message_count_month_5  message_count_month_6  message_count_month_7  \
0                  22.00                  60.00                  75.00   
1                    nan                    nan                    nan   

   message_count_month_8  message_count_month_9  message_count_month_10  \
0                  81.00                  57.00                   73.00   
1                    nan                    nan                     nan   

   message_count_month_11  message_count_month_12  
0                   58.00                   70.00  
1                     nan                     nan  

[2 rows x 48 columns]

___Вывод:___

Сделали сводную таблицу, чтобы узнать для каждого айди количество сообщений в каждый месяц.
Добавили эту информацию в базу клиентов

Смотрим на следующую базу:
### Таблица internet (информация об интернет-сессиях):

* *Приводим данные к нужным типам*
* *Находим и исправляем ошибки в данных (в том числе проверяем переменную Unnamed)*
* *Рассчитываем объем израсходованного интернет-трафика по месяцам;*
* *Добавляем информацию в массив df_users_join*

*Приводим данные к нужным типам*

In [41]:
# Обьект
df_internet['user_id'] = df_internet['user_id'].astype('object')

# Дата
df_internet['session_date'] = pd.to_datetime(df_internet[
    'session_date'], format='%Y-%m-%d')

# Сразу выделим месяц и год
df_internet['session_year'] = df_internet['session_date'].dt.year
df_internet['session_month'] = df_internet['session_date'].dt.month

# Проверяем
print_basic_info(df_internet,1,3,0)

 info  

<class 'pandas.core.frame.DataFrame'>
Int64Index: 149396 entries, 0 to 149395
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype         
---  ------         --------------   -----         
 0   id             149396 non-null  object        
 1   mb_used        149396 non-null  float64       
 2   session_date   149396 non-null  datetime64[ns]
 3   user_id        149396 non-null  object        
 4   session_year   149396 non-null  int64         
 5   session_month  149396 non-null  int64         
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 8.0+ MB
None
 head  



id    mb_used session_date user_id  session_year  session_month
0  1000_0     112.95   2018-11-25    1000          2018             11
1  1000_1    1052.81   2018-09-07    1000          2018              9
2  1000_2    1197.26   2018-06-25    1000          2018              6

 *Находим и исправляем ошибки в данных*

 ___id — уникальный номер сессии___

In [42]:
ft_name_count(df_internet,"id", 0,0,1)

#Все уникальные - отлично!

 id  

count       149396
unique      149396
top       1429_464
freq             1
Name: id, dtype: object


 ___mb_used — объём потраченного за сессию интернет-трафика (в мегабайтах)___

In [43]:
ft_name_count(df_internet,"mb_used", 0,0,1)

#Все уникальные - отлично!

 mb_used  

count    149396.00
mean        370.19
std         278.30
min           0.00
25%         138.19
50%         348.01
75%         559.55
max        1724.83
Name: mb_used, dtype: float64


 ___дата интернет-сессии___
 ___возьмем session_year, session_month ___

In [44]:
ft_name_count(df_internet,"session_year", 1,0,0)
ft_name_count(df_internet,"session_month", 1,1,0)

#Только 18 год. все месяцы. супер

 session_year  

2018         1.00
Name: session_year, dtype: float64
 session_month  

1          0.01
2          0.02
3          0.03
4          0.04
5          0.06
6          0.07
7          0.09
8          0.11
9          0.12
10         0.13
11         0.15
12         0.17
Name: session_month, dtype: float64


Есть нули - возможно отмененные запросы?-  за них человек не платит изначит при оценке тарифа они не нужны.

* *Уберем нули*

В тарифе при подсчете данные округялются вверх до мегабайт

* *Округлим вверх до мегабайт*

<div class="alert alert-success">
<h2> Комментарий наставника</h2>

Также предположение о том, откуда взялись данные нулевые значения высказано. Округление согласно правилам оператора произведено. 

</div>

In [45]:
#Убираем нули
df_internet = df_internet.query('mb_used != 0')

#Округлим вверх 
df_internet['mb_used'] = np.ceil(df_internet['mb_used'])

#проверяем
ft_name_count(df_internet,"mb_used", 0,0,1)

 mb_used  

count    129798.00
mean        426.58
std         255.60
min           1.00
25%         228.00
50%         401.00
75%         593.00
max        1725.00
Name: mb_used, dtype: float64


 ___user_id — идентификатор пользователя___

In [46]:
ft_name_count(df_internet,"user_id", 0,0,1)
#Менее 500 уникальных айди. Отлично.

 user_id  

count     129798
unique       497
top         1240
freq         731
Name: user_id, dtype: int64


___Вывод:___

Изменили типы данных где это необходимо. Выделили доп. переменые из дат.

Дублей в уникальном номере звонка нет.

Как и обещали - данные только с 2018 год. 
В первые месяцы года соединений меньше т.к. у нас выборка подключившихся за 18 год, а многие еше не подключились к тарифу.

497 уникальнвх номеров юзеров значит почти все пользовались интернетом.

**Корректировка**

___mb_used___

* Найдены нулевые значения (видимо не прошедшие запросы). Удалили кейсы с ними. За них человек не платит и значит при оценке тарифа они не нужны.
* При подсчете в тарифе идет округление вверх до мб. Округлили в базе аналогично.

___Unnamed: 0___

* переменная дублирует индекс базы. Удалили

*Рассчитываем объем израсходованного интернет-трафика по месяцам;*

In [47]:
# считаем
table_id_internet = df_internet.pivot_table(index=['user_id'], 
                                     columns='session_month',
                                     values='mb_used', 
                                     aggfunc='sum'
                                    )

table_id_internet = table_id_internet.reset_index()

table_id_internet.head(2)

session_month  user_id          1          2          3          4          5  \
0                 1000        nan        nan        nan        nan    2256.00   
1                 1001        nan        nan        nan        nan        nan   

session_month          6          7          8          9         10  \
0               23257.00   14016.00   14070.00   14581.00   14717.00   
1                    nan        nan        nan        nan        nan   

session_month         11         12  
0               14768.00    9827.00  
1               18452.00   14053.00

In [48]:
#сделаем нормальые названия

table_id_internet.columns = ['user_id',
                              'session_mb_month_1','session_mb_month_2',
                              'session_mb_month_3','session_mb_month_4',
                              'session_mb_month_5','session_mb_month_6',
                              'session_mb_month_7','session_mb_month_8',
                              'session_mb_month_9','session_mb_month_10',
                              'session_mb_month_11','session_mb_month_12',
                             ]

table_id_internet = table_id_internet.set_index('user_id')

table_id_internet.head(2)

session_mb_month_1  session_mb_month_2  session_mb_month_3  \
user_id                                                               
1000                    nan                 nan                 nan   
1001                    nan                 nan                 nan   

         session_mb_month_4  session_mb_month_5  session_mb_month_6  \
user_id                                                               
1000                    nan             2256.00            23257.00   
1001                    nan                 nan                 nan   

         session_mb_month_7  session_mb_month_8  session_mb_month_9  \
user_id                                                               
1000               14016.00            14070.00            14581.00   
1001                    nan                 nan                 nan   

         session_mb_month_10  session_mb_month_11  session_mb_month_12  
user_id                                                                 
1000                14717.00             14768.00              9827.00  
1001                     nan             18452.00             14053.00

*Добавляем информацию в массив df_users_join*

In [49]:
df_users_join = df_users_join.join(table_id_internet, on='user_id')

print(df_users_join.info(2))

df_users_join.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 60 columns):
 #   Column                  Non-Null Count  Dtype         
---  ------                  --------------  -----         
 0   user_id                 500 non-null    object        
 1   age                     500 non-null    int64         
 2   churn_date              38 non-null     datetime64[ns]
 3   city                    500 non-null    object        
 4   first_name              500 non-null    object        
 5   last_name               500 non-null    object        
 6   reg_date                500 non-null    datetime64[ns]
 7   tariff                  500 non-null    object        
 8   reg_year                500 non-null    int64         
 9   reg_month               500 non-null    int64         
 10  churn_year              38 non-null     float64       
 11  churn_month             38 non-null     float64       
 12  calls_min_month_1       42 non-null     float64   

user_id  age churn_date       city first_name  last_name   reg_date tariff  \
0    1000   52        NaT  Краснодар     Рафаил  Верещагин 2018-05-25  ultra   
1    1001   41        NaT     Москва       Иван       Ежов 2018-11-01  smart   

   reg_year  reg_month  ...  session_mb_month_3  session_mb_month_4  \
0      2018          5  ...                 nan                 nan   
1      2018         11  ...                 nan                 nan   

   session_mb_month_5  session_mb_month_6  session_mb_month_7  \
0             2256.00            23257.00            14016.00   
1                 nan                 nan                 nan   

   session_mb_month_8  session_mb_month_9  session_mb_month_10  \
0            14070.00            14581.00             14717.00   
1                 nan                 nan                  nan   

   session_mb_month_11  session_mb_month_12  
0             14768.00              9827.00  
1             18452.00             14053.00  

[2 rows x 60 columns]

___Вывод:___

Сделали сводную таблицу, чтобы узнать для каждого айди сумму использованных мб в каждый месяц.
Добавили эту информацию в базу клиентов.

<div class="alert alert-warning">
<h2> Комментарий наставника</h2>

Таблица с 60 колонками выглядит менее естественно, чем та, которая может быть получена при использовании другой структуры таблицы. Расчеты также станут гораздо легче. Однако и при использовании твоей таблицы вполне можно получить необходимые результаты. 

</div>

Смотрим на базу
### df_users_join:

* *Добавляем информацию из массиа df_tariffs*

* *Рассчитываем помесячную выручку с каждого пользователя* (вычтите бесплатный лимит из суммарного количества звонков, сообщений и интернет-трафика; остаток умножьте на значение из тарифного плана; прибавьте абонентскую плату, соответствующую тарифному плану).

*Добавляем информацию из массиа df_tariffs*

In [50]:
# смотрим сходится ли с описанием
df_tariffs.head()
# сходится

messages_included  mb_per_month_included  minutes_included  \
0                 50                  15360               500   
1               1000                  30720              3000   

   rub_monthly_fee  rub_per_gb  rub_per_message  rub_per_minute tariff_name  
0              550         200                3               3       smart  
1             1950         150                1               1       ultra

In [51]:
df_users_join = df_users_join.merge(df_tariffs, 
                                   left_on='tariff', 
                                   right_on='tariff_name')
print(df_users_join.info())

df_users_join.head(5)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 500 entries, 0 to 499
Data columns (total 68 columns):
 #   Column                  Non-Null Count  Dtype         
---  ------                  --------------  -----         
 0   user_id                 500 non-null    object        
 1   age                     500 non-null    int64         
 2   churn_date              38 non-null     datetime64[ns]
 3   city                    500 non-null    object        
 4   first_name              500 non-null    object        
 5   last_name               500 non-null    object        
 6   reg_date                500 non-null    datetime64[ns]
 7   tariff                  500 non-null    object        
 8   reg_year                500 non-null    int64         
 9   reg_month               500 non-null    int64         
 10  churn_year              38 non-null     float64       
 11  churn_month             38 non-null     float64       
 12  calls_min_month_1       42 non-null     float64   

user_id  age churn_date         city first_name  last_name   reg_date  \
0    1000   52        NaT    Краснодар     Рафаил  Верещагин 2018-05-25   
1    1003   23        NaT       Москва      Белла   Белякова 2018-08-17   
2    1004   68        NaT  Новокузнецк    Татьяна   Авдеенко 2018-05-14   
3    1013   36        NaT      Иваново      Борис  Андреенко 2018-11-14   
4    1016   58        NaT         Омск     Марица   Сазонова 2018-11-21   

  tariff  reg_year  reg_month  ...  session_mb_month_11  session_mb_month_12  \
0  ultra      2018          5  ...             14768.00              9827.00   
1  ultra      2018          8  ...             11368.00             10132.00   
2  ultra      2018          5  ...             15631.00             18038.00   
3  ultra      2018         11  ...              9790.00             20755.00   
4  ultra      2018         11  ...              7388.00             19446.00   

   messages_included  mb_per_month_included  minutes_included  \
0               1000                  30720              3000   
1               1000                  30720              3000   
2               1000                  30720              3000   
3               1000                  30720              3000   
4               1000                  30720              3000   

   rub_monthly_fee  rub_per_gb  rub_per_message  rub_per_minute  tariff_name  
0             1950         150                1               1        ultra  
1             1950         150                1               1        ultra  
2             1950         150                1               1        ultra  
3             1950         150                1               1        ultra  
4             1950         150                1               1        ultra  

[5 rows x 68 columns]

*Рассчитываем помесячную выручку с каждого пользователя* 
* вычтите бесплатный лимит из суммарного количества звонков, сообщений и интернет-трафика
* остаток умножьте на значение из тарифного плана
* прибавьте абонентскую плату, соответствующую тарифному плану

*вычтите бесплатный лимит из суммарного количества звонков, сообщений и интернет-трафика*

In [52]:
#посмотрим экстра минуты, смс и трафик 
i = 1
while i <= 12:
    df_users_join['extra_min_month_'+ str(i)] =  df_users_join[
        'calls_min_month_'+ str(i)] - df_users_join['minutes_included']
    df_users_join['extra_mb_month_'+ str(i)] =  df_users_join[
        'session_mb_month_'+ str(i)] - df_users_join['mb_per_month_included']
    df_users_join['extra_messages_month_'+ str(i)] = df_users_join[
        'message_count_month_'+ str(i)] - df_users_join['messages_included'] 
    i += 1

#посмотрим пример
ft_name_count(df_users_join,"extra_min_month_7", 0,0,1)

 extra_min_month_7  

count       288.00
mean       -797.76
std        1097.11
min       -2988.00
25%       -2175.75
50%        -196.50
75%          -7.00
max         339.00
Name: extra_min_month_7, dtype: float64


Обнулим недоборы и удалим данные для тех месяцев, когда люди не были подключены    

In [53]:
i = 1
while i <= 12:
    df_users_join['extra_min_month_'+ str(i)] = df_users_join[
        'extra_min_month_'+ str(i)].where(df_users_join['extra_min_month_'+ str(i)] >= 0 ,0)
    df_users_join['extra_min_month_'+ str(i)] = df_users_join[
        'extra_min_month_'+ str(i)].where((df_users_join['reg_month'] <= i) & (
                                          (df_users_join['churn_month'] >= i) |
                                          (df_users_join['churn_month'].isnull() == True))
                                          , None)
    df_users_join['extra_mb_month_'+ str(i)] = df_users_join[
        'extra_mb_month_'+ str(i)].where(df_users_join['extra_mb_month_'+ str(i)] >= 0 ,0)
    df_users_join['extra_mb_month_'+ str(i)] = df_users_join[
        'extra_mb_month_'+ str(i)].where((df_users_join['reg_month'] <= i) & (
                                          (df_users_join['churn_month'] >= i) |
                                          (df_users_join['churn_month'].isnull() == True))
                                          , None)
    df_users_join['extra_messages_month_'+ str(i)] = df_users_join[
        'extra_messages_month_'+ str(i)].where(df_users_join[
        'extra_messages_month_'+ str(i)] >= 0 ,0)
    df_users_join['extra_messages_month_'+ str(i)] = df_users_join[
        'extra_messages_month_'+ str(i)].where((df_users_join['reg_month'] <= i) & (
                                          (df_users_join['churn_month'] >= i) |
                                          (df_users_join['churn_month'].isnull() == True))
                                          , None)
    i += 1

#посмотрим пример
ft_name_count(df_users_join,"extra_mb_month_7", 0,0,1)

 extra_mb_month_7  

count        292.00
unique       126.00
top            0.00
freq         166.00
Name: extra_mb_month_7, dtype: float64


___Досчитываем arpu___ 
* остаток минтут/смс/мб на умножьте на значение из тарифного плана (при этом округление по ГБ т.к. оплата по ГБ)
* прибавьте абонентскую плату, соответствующую тарифному плану


In [54]:
#посмотрим экстра минуты, смс и трафик 
i = 1
while i <= 12:
    df_users_join['arpu_month_'+ str(i)] =  df_users_join['rub_monthly_fee'] + df_users_join[
        'extra_min_month_'+ str(i)]*df_users_join['rub_per_minute'] + df_users_join[
        'extra_messages_month_'+ str(i)]*df_users_join[
        'rub_per_message'] + np.ceil(df_users_join[
        'extra_mb_month_'+ str(i)].where((df_users_join['extra_mb_month_'+ str(i)].isnull() 
                                         != True), 0) / 1024)*df_users_join['rub_per_gb']
    df_users_join['arpu_month_'+ str(i)] = df_users_join[
        'arpu_month_'+ str(i)].where((df_users_join[
        'reg_month'] <= i) & ((df_users_join['churn_month'] >= i) |
                              (df_users_join['churn_month'].isnull() == True)), None)   
    i += 1

#посмотрим пример
print(df_users_join.query('tariff == "ultra"')['arpu_month_11'].describe())
print(df_users_join.query('tariff == "smart"')['arpu_month_11'].describe())

count        134.00
unique        13.00
top         1950.00
freq         113.00
Name: arpu_month_11, dtype: float64
count        316.00
unique       164.00
top          550.00
freq          63.00
Name: arpu_month_11, dtype: float64


Убьем промежуточные переменные (extra) и сделаем arpu ньюмериком

In [55]:
i = 1
while i <= 12:
    df_users_join= df_users_join.drop(['extra_messages_month_'+ str(i), 
                                       'extra_min_month_'+ str(i),
                                      'extra_mb_month_'+ str(i)], axis=1)
    df_users_join['arpu_month_'+ str(i)] = df_users_join[
        'arpu_month_'+ str(i)].astype('float')
    i += 1
    
df_users_join = df_users_join.drop(['tariff_name'], axis=1)

print(df_users_join.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 500 entries, 0 to 499
Data columns (total 79 columns):
 #   Column                  Non-Null Count  Dtype         
---  ------                  --------------  -----         
 0   user_id                 500 non-null    object        
 1   age                     500 non-null    int64         
 2   churn_date              38 non-null     datetime64[ns]
 3   city                    500 non-null    object        
 4   first_name              500 non-null    object        
 5   last_name               500 non-null    object        
 6   reg_date                500 non-null    datetime64[ns]
 7   tariff                  500 non-null    object        
 8   reg_year                500 non-null    int64         
 9   reg_month               500 non-null    int64         
 10  churn_year              38 non-null     float64       
 11  churn_month             38 non-null     float64       
 12  calls_min_month_1       42 non-null     float64   

In [56]:
#смотрим пример в разрезе тарифов, чтобы проверить минимумы

print(df_users_join.query('tariff == "ultra"')['arpu_month_10'].describe())
print(df_users_join.query('tariff == "smart"')['arpu_month_10'].describe())

count       123.00
mean       2067.07
std         390.56
min        1950.00
25%        1950.00
50%        1950.00
75%        1950.00
max        4800.00
Name: arpu_month_10, dtype: float64
count       294.00
mean       1369.62
std         848.18
min         550.00
25%         560.50
50%        1150.00
75%        1834.00
max        4231.00
Name: arpu_month_10, dtype: float64


___Вывод:___

Рассчитали arpu для каждого месяца (с учетом, что что не все клиенты были подключены к тарифу в течении всего года).

<div class="alert alert-warning">
<h2> Комментарий наставника</h2>

Финальная таблица получена. Стоит убрать из нее излишнюю информацию в виде имени или фамилии клиента. Такая информация никак не поможет нам в анализе, поэтому хранить ее повторно не стоит. Информация о тарифах у нас уже есть в таблице tariffs. Дублировать ее не стоит. Также выручку стоит сделать целочисленным показателем. 

</div>

### Шаг 3. Проанализируйте данные

Опишите поведение клиентов оператора, исходя из выборки. 
* Сколько минут разговора, сколько сообщений и какой объём интернет-трафика требуется пользователям каждого тарифа в месяц? 
* Посчитайте среднее количество, дисперсию и стандартное отклонение. 
* Постройте гистограммы. Опишите распределения.

*Сколько минут разговора, сколько сообщений и какой объём интернет-трафика требуется пользователям каждого тарифа в месяц?*

In [57]:
# суммируем все месяца
i = 1

df_users_join['calls_min'] = 0 
df_users_join['calls_count'] = 0 
df_users_join['session_mb'] = 0
df_users_join['message_count'] = 0 
df_users_join['arpu'] = 0

while i <= 12:
    df_users_join['calls_min'] += df_users_join[
        'calls_min_month_' + str(i)].where((df_users_join[
    'calls_min_month_' + str(i)].isnull() != True), 0) 
    df_users_join['calls_count'] += df_users_join[
        'calls_count_month_' + str(i)].where((df_users_join[
    'calls_count_month_' + str(i)].isnull() != True), 0) 
    df_users_join['session_mb'] += df_users_join[
        'session_mb_month_' + str(i)].where((df_users_join[
    'session_mb_month_' + str(i)].isnull() != True), 0) 
    df_users_join['message_count'] += df_users_join[
        'message_count_month_' + str(i)].where((df_users_join[
    'message_count_month_' + str(i)].isnull() != True), 0) 
    df_users_join['arpu'] += df_users_join[
        'arpu_month_' + str(i)].where((df_users_join[
    'arpu_month_' + str(i)].isnull() != True), 0) 
    
    i += 1
    
# делим на количество месяцев на тарифе 
df_users_join['calls_min'] = df_users_join[
    'calls_min'] /(df_users_join[
    'churn_month'].where((df_users_join[
    'churn_month'].isnull() != True), 12) - df_users_join['reg_month'] + 1)
df_users_join['calls_count'] = df_users_join[
    'calls_count'] /(df_users_join[
    'churn_month'].where((df_users_join[
    'churn_month'].isnull() != True), 12) - df_users_join['reg_month'] + 1)
df_users_join['session_mb'] = df_users_join[
    'session_mb'] /(df_users_join[
    'churn_month'].where((df_users_join[
    'churn_month'].isnull() != True), 12) - df_users_join['reg_month'] + 1)
df_users_join['message_count'] = df_users_join[
    'message_count'] /(df_users_join[
    'churn_month'].where((df_users_join[
    'churn_month'].isnull() != True), 12) - df_users_join['reg_month'] + 1)
df_users_join['arpu'] = df_users_join[
    'arpu'] /(df_users_join[
    'churn_month'].where((df_users_join[
    'churn_month'].isnull() != True), 12) - df_users_join['reg_month'] + 1)


#Проверим
ft_name_count(df_users_join,"calls_min", 0,0,1)
ft_name_count(df_users_join,"calls_count", 0,0,1)
ft_name_count(df_users_join,"session_mb", 0,0,1)
ft_name_count(df_users_join,"message_count", 0,0,1)
ft_name_count(df_users_join,"arpu", 0,0,1)

 calls_min  

count       500.00
mean        449.98
std         203.36
min           0.00
25%         317.33
50%         442.00
75%         558.08
max        1179.36
Name: calls_min, dtype: float64
 calls_count  

count       500.00
mean         50.54
std          22.87
min           0.00
25%          35.00
50%          49.73
75%          62.70
max         140.50
Name: calls_count, dtype: float64
 session_mb  

count       500.00
mean      17140.45
std        5740.03
min           0.00
25%       13820.79
50%       16690.29
75%       19563.58
max       38502.00
Name: session_mb, dtype: float64
 message_count  

count       500.00
mean         38.64
std          35.06
min           0.00
25%          11.00
50%          30.50
75%          58.00
max         192.00
Name: message_count, dtype: float64
 arpu  

count       500.00
mean       1553.68
std         637.37
min         550.00
25%        1007.80
50%        1621.33
75%        1950.00
max        4333.33
Name: arpu, dtype: float64


*Посчитайте среднее количество, дисперсию и стандартное отклонение.*

In [58]:
#табличка о тарифе, для информации

info_table = pd.DataFrame()
for i in ["minutes_included",'mb_per_month_included',"messages_included",
          "rub_monthly_fee","rub_per_gb","rub_per_message","rub_per_minute","rub_monthly_fee"]:
    for k in df_users_join['tariff'].unique():
        info_table.loc[i,k] = str(int(df_users_join[df_users_join['tariff'] == k][i].mean()))
print(bold(),colored("Информация по тарифам",'green'), bold_end())
print(info_table)
print("\n")

 Информация по тарифам 
                       ultra  smart
minutes_included        3000    500
mb_per_month_included  30720  15360
messages_included       1000     50
rub_monthly_fee         1950    550
rub_per_gb               150    200
rub_per_message            1      3
rub_per_minute             1      3




In [59]:
i_table = pd.DataFrame()
for i in ["calls_min","calls_count",
          "session_mb","message_count","arpu"]:
    for k in df_users_join['tariff'].unique():
        i_table.loc[str(i)+"_mean",k] = df_users_join[df_users_join['tariff'] == k][i].mean()
        #добавляем ddof = 1, т.к. у нас только часть генеральной совокупности.
        i_table.loc[str(i)+"_var",k] = np.var(df_users_join[df_users_join['tariff'] == k][i], ddof=1) 
        i_table.loc[str(i)+"_std",k] = np.std(df_users_join[df_users_join['tariff'] == k][i], ddof=1)
        #i_table.loc['mean_min_std', k] = i_table.loc['mean',k] - i_table.loc['std',k]   
        #i_table.loc['mean_plus_std', k] = i_table.loc['mean',k] + i_table.loc['std',k]   
        i_table.loc[str(i)+"_ratio_use", k] = df_users_join[((df_users_join[i] != 0) & (df_users_join[
            'tariff'] == k))][i].count() / df_users_join[df_users_join['tariff'] == k][i].count()
        
print(i_table)

                              ultra       smart
calls_min_mean               524.28      418.44
calls_min_var              80736.81    21475.74
calls_min_std                284.14      146.55
calls_min_ratio_use            0.96        0.99
calls_count_mean              58.88       47.01
calls_count_var             1029.84      268.19
calls_count_std               32.09       16.38
calls_count_ratio_use          0.96        0.99
session_mb_mean            19461.34    16155.23
session_mb_var          71310459.73 13553609.08
session_mb_std              8444.55     3681.52
session_mb_ratio_use           0.99        1.00
message_count_mean            53.67       32.26
message_count_var           2154.90      703.88
message_count_std             46.42       26.53
message_count_ratio_use        0.83        0.86
arpu_mean                   2086.50     1327.51
arpu_var                   90024.38   368949.21
arpu_std                     300.04      607.41
arpu_ratio_use                 1.00     

<div class="alert alert-warning">
<h2> Комментарий наставника</h2>

Будет здорово, если ты объединишь все показатели в единую таблицу. Удобнее работать с данными, собранными вместе в одну таблицу. 

</div>

Люди на ultra пользуются услугами меньше квот, а smart платят сверх АП.

Клиентов это устраивает? Посмотрим на % ушедших

In [60]:
#Процент уходов до конца года 
i_table = pd.DataFrame()

for k in df_users_join['tariff'].unique():
        i_table.loc['ratio',k] = df_users_join[df_users_join[
            'tariff'] == k]['tariff'].count()/df_users_join['tariff'].count()  
        i_table.loc['churn_ratio',k] = df_users_join[df_users_join[
            'tariff'] == k]['churn_month'].count()/df_users_join[df_users_join[
            'tariff'] == k]['tariff'].count()  
print(bold(),colored("",'blue'), bold_end())
print(i_table)
print("\n")

  
                 ultra      smart
ratio             0.30       0.70
churn_ratio       0.10       0.07




___Вывод:___

Не все все клиенты были подключены к тарифу в течении всего года.
* Поэтому, мы не можем сложить все данные по клиентам за год и сравнивать их.
* Чтобы посмотреть профиль по каждому клиенту, мы посчитали средний показатель по каждому из клиентов за месяц использования тарифом.


__Тариф ultra__

* Тариф пользуется меньшей популярностью, чем тариф- конкурент. Только треть подключилась к нему

* Клиенты в среднем используют до 800 минут разговора в месяц из 3000 включенных в тариф. Что меньше 1/3 о тарифа.

* С интернетом указанным в тарифе другая история. Он обычно используется почти полностью. (в среднем до 2.7 ГБ из 3 ГБ входящих в тариф), что может говорить, о том что именно интернет - первоочередная причина выбора тарифа.

* В тариф включены 1000 сообщений, тариф используется только 1 из 10 .

* Среднее ARPU в месяц (1950 - 2386) сравнимо с абонентской платой. Переплаты скорее всего связанны с закупкой ГБ сверх тарифа.

* Процент уходов выше, чем другом тарифе. С учетом выборок разница не значимая, но в будущем надо следить за этим.


__Тариф  smart__

* Клиенты в среднем используют 272 - 565 минут разговора в месяц включая 500 включенные тариф. Значит клиенты склонны превышать количество минут, указанное в тарифе.

* Тариф пользуется большей популярностью, чем тариф - конкурент.7 из 10 подключились именно к нему

* Клиенты в среднем используют 1,2 - 2 ГБ , из 1,5 включенных в тариф. Значит клиенты склонны докупать дополнительные  ГБ сверх тарифа.

* В тариф включены 50 сообщений, тариф используется все или почти все, также есть доля использующих  сообщения вверх тарифа. 

* Среднее ARPU в месяц (720 - 1934) сильно выше АП в 550 рублей. Клиентам не хватает услуг, входящих в тариф. 



<div class="alert alert-success">
<h2> Комментарий наставника</h2>

Статистические показатели получены. Здорово, что ты сравниваешь тарифы между собой. Именно сравнения помогут нам ответить на вопрос о том, какой из тарифов выгоднее.

</div>

*Постройте гистограммы. Опишите распределения.*

Сделаем функцию ___ft_box_comp(base, name, cross, title,labelx, labely)___, для вывода графика боксплот в разрезе

6 входных параметров

* *base* - название базы данных
* *name* - имя переменной в базе
* *cross* - имя переменной, в разрезе которой смотрим
* *title* - название таблицы
* *labelx* - лейбл X
* *labely* - лейбл Y

In [61]:
def add_median(df,group_col,y):
    mean_dict = {grp[0]:grp[1][y].median() for grp in df.groupby(group_col)}
    xticklabels = [x.get_text() for x in plt.gca().get_xticklabels()]
    for (x, xticklabel) in enumerate(xticklabels):
        plt.text(x, mean_dict[xticklabel]*1.03, "median: "+str(int(mean_dict[xticklabel])),
                 horizontalalignment='center', fontdict={'size':10}, color='white')
def add_quantile(df,group_col,y,q,label):
    qt_dict = {grp[0]:grp[1][y].quantile(q) for grp in df.groupby(group_col)}
    xticklabels = [x.get_text() for x in plt.gca().get_xticklabels()]
    for (x, xticklabel) in enumerate(xticklabels):
        plt.text(x, qt_dict[xticklabel]*1.03, label + str(int(qt_dict[xticklabel])),
                 horizontalalignment='center', fontdict={'size':10}, color='black')    
def add_QR_max(df,group_col,y,label):
    qt_dict = {grp[0]:(grp[1][y].quantile(0.75) + 
                       ((grp[1][y].quantile(0.75)- grp[1][y].quantile(0.25))*1.5)) 
               for grp in df.groupby(group_col)}
    xticklabels = [x.get_text() for x in plt.gca().get_xticklabels()]
    for (x, xticklabel) in enumerate(xticklabels):
        plt.text(x, qt_dict[xticklabel]*1.03, label + str(int(qt_dict[xticklabel])),
                 horizontalalignment='center', fontdict={'size':10}, color='black')  
def add_QR_min(df,group_col,y,label):
    qt_dict = {grp[0]:(grp[1][y].quantile(0.25) -
                       ((grp[1][y].quantile(0.75)- grp[1][y].quantile(0.25))*1.5)) 
               for grp in df.groupby(group_col)}
    xticklabels = [x.get_text() for x in plt.gca().get_xticklabels()]
    for (x, xticklabel) in enumerate(xticklabels):
        plt.text(x, qt_dict[xticklabel]*1.00, label + str(int(qt_dict[xticklabel])),
                 horizontalalignment='center', fontdict={'size':10}, color='black')
        
def ft_box_comp(base, name, cross, title,labelx, labely):
    sns.boxplot(x=cross, y=name, data=base, notch=False)
    add_median(base,cross,name)  
    add_quantile(base,cross,name,0.25,"Q1: ")    
    add_quantile(base,cross,name,0.75,"Q3: ")    
    add_QR_max(base,cross,name,"Q3 + 1.5 IQR: ")
    add_QR_min(base,cross,name,"Q1 - 1.5 IQR: ")       
    plt.title(title, fontsize=15)
    plt.xlabel(labelx)
    plt.ylabel(labely)
    plt.ylim((min(base[name]) - (np.std(base[name])*2 )), 
             (max(base[name]) + (np.std(base[name])*2 )))
    plt.show()

In [ ]:
<!-- Сделаем функцию ___ft_hist_comp(base, name, cross, title,labelx, labely)___, для вывода графика боксплот в разрезе

6 входных параметров

* *base* - название базы данных
* *name* - имя переменной в базе
* *cross* - имя переменной, в разрезе которой смотрим
* *title* - название таблицы
* *labelx* - лейбл X
* *labely* - лейбл Y -->

def ft_hist_comp(base, name, cross,title,labelx, labely):
    for i in base[cross].unique():
        base[base[cross] == i][name].hist(bins = 50, label = 
                                              str(i), alpha=0.7, density=True)
    plt.xlabel(labelx)
    plt.ylabel(labely)
    plt.title(title, fontsize=15) 
    plt.legend()
    plt.show()

Количество минут разговора в месяц 

<div class="alert alert-warning">
<h2> Комментарий наставника</h2>

Очень крутая задумка с подписями основных показателей. Только линия на boxplot, это не среднее значение, а медиана, а усы по умолчанию длиной Q1-1.5IQR и Q3+1.5IQR. В остальном все здорово. 

</div>

In [4]:
ft_box_comp(df_users_join, name = 'calls_min', cross = 'tariff',
                title ='Количество минут разговора в месяц (в разрезе тарифов)',
           labelx = 'Тарифы', labely = 'Минут')

ft_hist_comp(df_users_join, name = 'calls_min', cross = 'tariff',
             title ='Количество минут разговора в месяц (в разрезе тарифов)',
           labely = '% от кейсов', labelx = 'Минут')

NameError: name 'ft_box_comp' is not defined

In [ ]:
df_users_join2.info()

In [ ]:
#Альтерналичная версия
import plotly.graph_objects as go

df_users_join2 = df_users_join2.reset_index()

y = df_users_join2['tariff'] 

fig = go.Figure()
fig.add_trace(go.Box(
    x=df_users_join2['duration_sum'] ,
    y=y,
    name='smart',
    marker_color='#3D9970'
))
fig.update_layout(
    xaxis=dict(title='normalized moisture', zeroline=False),
    boxmode='group'
)

fig.update_traces(orientation='h') # horizontal box plots
fig.show()

In [ ]:
import plotly.graph_objects as go

x_data = ['ultra', 'smart']


y_data = [df_users_join2[df_users_join2['tariff'] == 'ultra']['duration_sum'], 
          df_users_join2[df_users_join2['tariff'] == 'smart']['duration_sum']]

colors = ['rgba(93, 164, 214, 0.5)', 'rgba(255, 144, 14, 0.5)']

fig = go.Figure()

for xd, yd, cls in zip(x_data, y_data, colors):
        fig.add_trace(go.Box(
            y=yd,
            name=xd,
            boxpoints='all',
            jitter=0.5,
            whiskerwidth=0.2,
            fillcolor=cls,
            marker_size=2,
            line_width=1)
        )

fig.update_layout(
    title='Граффик',
    margin=dict(
        l=40,
        r=30,
        b=80,
        t=100,
    ),
    paper_bgcolor='rgb(243, 243, 243)',
    plot_bgcolor='rgb(243, 243, 243)',
    showlegend=False
)

fig.show()

Количество звонков в месяц 

In [ ]:
ft_box_comp(df_users_join, name = 'calls_count', cross = 'tariff',
                title ='Количество звонков в месяц (в разрезе тарифов)',
           labelx = 'Тарифы', labely = 'Минут')

ft_hist_comp(df_users_join, name = 'calls_count', cross = 'tariff',
             title ='Количество звонков в месяц (в разрезе тарифов)',
           labely = '% от кейсов', labelx = 'Минут')

Количество использованных мб в месяц 

In [ ]:
ft_box_comp(df_users_join, name = 'session_mb', cross = 'tariff',
                title ='Траффик за месяц (в разрезе тарифов)',
           labelx = 'Тарифы', labely = 'Мегабайт')

ft_hist_comp(df_users_join, name = 'session_mb', cross = 'tariff',
             title ='Траффик за месяц (в разрезе тарифов)',
           labely = '% от кейсов', labelx = 'Мегабайт')

Количество смс в месяц 

In [ ]:
ft_box_comp(df_users_join, name = 'message_count', cross = 'tariff',
                title ='Количество сообщений в месяц (в разрезе тарифов)',
           labelx = 'Тарифы', labely = 'Сообщений')

ft_hist_comp(df_users_join, name = 'message_count', cross = 'tariff',
             title ='Количество сообщений в месяц (в разрезе тарифов)',
           labely = '% от кейсов', labelx = 'Сообщений')

Сколько платят за месяц

In [ ]:
ft_box_comp(df_users_join, name = 'arpu', cross = 'tariff',
                title ='Траты в рублях за месяц (в разрезе тарифов)',
           labelx = 'Тарифы', labely = 'Рублей')

ft_hist_comp(df_users_join, name = 'arpu', cross = 'tariff',
             title ='Траты в рублях за месяц (в разрезе тарифов)',
           labely = '% от кейсов', labelx = 'Рублей')

__Вывод:__

Пользователи тарифа Ultra больше разговаривают по телефону, чем клиенты Smart. В среднем на 100 минут.
50% клиентов Smart разговаривают от 315 до 518 минут в день. (Т.е. + 100 минут от среднего (418 минут).
Клиенты Ultra менее однородны. 50% клиентов Smart разговаривают от 320 до 746 минут в день. 

Количество звонков в месяц среди клиентов тарифов не сильно различается. В среднем на 10 звонков. Клиенты Ultra все еще менее консистентны, но по не так остро выражается в данном показателе.

Клиенты Ultra используют интернет более активно. В среднем на 0.3 Гб в месяц больше. Как в других показателях видно, что клиенты Ultra менее константы в использовании тарифа и сползут вплоть до 3.8 ГБ, против 2.3 ГБ среди клиентов Smart.

Сообщения наименее популярны. Ими используются меньшая долей пользователей (83% для Ultra и 86% для Smart).
В среднем клиенты Ultra больше посылают сообщений ( на 20 штук). Клиенты Ultra все еще менее консистентны, но по не так остро выражается в данном показателе.

Пользователи тарифа Ultra больше платят в месяц, чем клиенты Smart. Это обоснованно в первую очередь различным минимумом оплаты в месяц - различной абонентской платой.
Пользователи тарифа Ultra в подавляющем случае не платят сверх АП.
В то время как абоненты Smart в среднем платят более чем в 2 раза более АП.

<div class="alert alert-success">
<h2> Комментарий наставника</h2>

Базовые статистические параметры получены. Приведены все необходимые графики. Здорово, что графики для одинаковых услуг тарифов приведены на одном рисунке. Так удобнее сравнивать тарифы. Возможно, тебе будет интересно изучить библиотеку plotly для визуализации. Такой же график boxplot с подписями там получается куда проще. Вот ссылка на [пример](https://plotly.com/python/box-plots/).

</div>

### Шаг 4. Проверьте гипотезы

* 		средняя выручка пользователей тарифов «Ультра» и «Смарт» различается;
* 		средняя выручка пользователей из Москвы отличается от выручки пользователей из других регионов;

Пороговое значение alpha задайте самостоятельно.<br>
Поясните:

* 		как вы формулировали нулевую и альтернативную гипотезы;
* 		какой критерий использовали для проверки гипотез и почему.

*средняя выручка пользователей тарифов «Ультра» и «Смарт» различается*


* Среднюю выручку смотрим по переменной arpu - среднюю по всем месяцам использования.


* ___Исходя из средних значений по переменной, можно предположить, что средняя выручка из тарифа Ультра, выше средней выборки тарифа Смарт___, для того чтобы это проверить мы выдвинем несколько гипотез.<br>
1) Средняя выручка тарифов не различается.<br>
2) Средняя выручка тарифа Ультра значимо ниже средней выручки тарифа Смарт.


* Цена это один из основопологающий фактор, для  оценки продукта, поэтому мы должны допрассмотреть минимальнуй ошибку. Попробуем исходить из вероятности 99%, а значит alpha = .01.

Средняя выручка тарифов не различается.<br>
* Используем alpha = .01
* Гипотеза 2 стороняя

In [ ]:
alpha = .01 

results = st.ttest_ind(
    df_users_join[df_users_join['tariff'] == 'ultra']['arpu'], 
    df_users_join[df_users_join['tariff'] == 'smart']['arpu'])

print('p-значение:', results.pvalue)
    
if (results.pvalue < alpha):
    print("Отвергаем нулевую гипотезу, значит средняя выручка тарифов различается.")
else:
    print("Не получилось отвергнуть нулевую гипотезу, и не "+ 
          "знаем различается ли или нет средняя выручка тарифов")


Средняя выручка тарифа Ультра значимо ниже средней выручки тарифа Смарт..<br>
* Используем alpha = .01
* Гипотеза 1 стороняя

In [ ]:
alpha = .01 

results = st.ttest_ind(
    df_users_join[df_users_join['tariff'] == 'ultra']['arpu'], 
    df_users_join[df_users_join['tariff'] == 'smart']['arpu'])

print('p-значение:', results.pvalue)
    
print(bold(),'\n Средние значения (в рублях) \n', bold_end(),
      "ultra:", int(round(df_users_join[df_users_join['tariff'] == 'ultra'][
          'arpu'].mean(),0)), "руб.\n",
      " smart:", int(round(df_users_join[df_users_join['tariff'] == 'smart'][
          'arpu'].mean(),0)),"руб.")
    
if (results.pvalue / 2 < alpha) and (df_users_join[df_users_join['tariff'] == 'ultra'][
    'arpu'].mean() > df_users_join[df_users_join['tariff'] == 'smart']['arpu'].mean()):
    print("Отвергаем нулевую гипотезу, что средняя выручка тарифа Ультра значимо "+
          "ниже средней выручки тарифа Смарт.")
else:
    print("Не получилось отвергнуть нулевую гипотезу")

<div class="alert alert-success">
<h2> Комментарий наставника</h2>

Гипотезы сформулированы и проверены верно. Здорово, что ты также провела и односторонний тест. 

</div>

*средняя выручка пользователей из Москвы отличается от выручки пользователей из других регионов*

Проверим, корректно ли смотреть в целом или только внутри тарифов.

Для этого посчитаем распределение по городам и тарифам в процентах

In [ ]:
#Переменная для каунта
df_users_join['total'] = 1

df_users_join['city_type'] = df_users_join['city'].where(df_users_join[
    'city'] == 'Москва', 'Другой город')

#табличка
table = df_users_join.pivot_table(index=['city_type'], columns=
                                  ['tariff'], values='total', aggfunc='count')
table = table.reset_index()

#суммируем кейсы
table.loc[2] = ['base',sum(table['smart']), sum(table['ultra'])]

i = 0
while i < len(table) - 1:
    table.loc[i, ['smart']] = table.loc[i, ['smart']] /table.loc[len(table) - 1, ['smart']]
    table.loc[i, ['ultra']] = table.loc[i, ['ultra']] /table.loc[len(table) - 1, ['ultra']]
    i = i + 1

print(table)

Выборка не большая так же как и разница в процентах.

Разница не значимая в тарифах.

Поэтому можем вместе смотреть.

Также посмотрим на средние, чтобы оценить и составить гипотезы.

In [ ]:
print("Среднее по Москве",int(df_users_join.query('city == "Москва"')['arpu'].mean()), "р.")
print("Среднее по другим городам",int(df_users_join.query('city != "Москва"')['arpu'].mean()), "р.")

Средние не сильно различаются + у нас выборки не большие. 
Врятли мы сможем определить различия. <br>Но это не говорит о том, что их нет. Возможно выборки просто не хватает, для их определения.
Спускаться до городов тоже нет смысла. Т.к. выборка еще меньше. Хотя можно попробовать СПБ вытащить в карегорию "Столицы".

* на 99% точно не поймаем разницу, попробуем поймать с вероятностью 95% ( т.е. alpha = .05)
* Гитотеза 2 стороняя (средняя выручка пользователей из Москвы не отличается от выручки пользователей из других регионов)

In [ ]:
alpha = .05
    
results = st.ttest_ind(
    df_users_join.query('tariff == "ultra" and city == "Москва"')['arpu'], 
    df_users_join.query('tariff == "ultra" and city != "Москва"')['arpu'])

print('p-значение:', results.pvalue)
    
if (results.pvalue < alpha):
    print("Отвергаем нулевую гипотезу")
else:
    print("Не получилось отвергнуть нулевую гипотезу")


Гипотезу не получилось опровергнуть.
Попробуем соединить с СПБ.

In [ ]:
print("Среднее по Столицам",int(df_users_join.query(
    'city == "Москва" or city == "Санкт-Петербург"')['arpu'].mean()), "р.")
print("Среднее по другим городам",int(df_users_join.query(
    'city != "Москва" and city != "Санкт-Петербург"')['arpu'].mean()), "р.")

Еще меньше разницы. Дальше копать не будем.

А если всетаки посмотреть по каждому тарифу?

In [ ]:
alpha = .05
    
results = st.ttest_ind(
    df_users_join.query('tariff == "ultra" and city == "Москва"')['arpu'], 
    df_users_join.query('tariff == "ultra" and city != "Москва"')['arpu'])

print('p-значение:', results.pvalue)
    
if (results.pvalue < alpha):
    print("Отвергаем нулевую гипотезу")
else:
    print("Не получилось отвергнуть нулевую гипотезу")


In [ ]:
alpha = .05 

results = st.ttest_ind(
    df_users_join.query('tariff == "smart" and city == "Москва"')['arpu'], 
    df_users_join.query('tariff == "smart" and city != "Москва"')['arpu'])

print('p-значение:', results.pvalue)
    
if (results.pvalue < alpha):
    print("Отвергаем нулевую гипотезу")
else:
    print("Не получилось отвергнуть нулевую гипотезу")

Мы не можем сказать отличается или нет выручка в Москве от Других городов

#### Вывод

Мы отвергли гипотезу, что средняя выручка тарифа Ultra значимо не отличается от средней выручки тарифа Smart.<br>
А также гипотезу, что средняя выручка тарифа Ultra значимо ниже средней выручки тарифа Smart.<br>
Следовательно ___средняя выручка из тарифа Ultra, выше средней выборки тарифа Smart___ об этом мы можем говорить с вероятностью 99%.

Проверили, что распределение тарифов в Москве против Других городов отличаются не сильно и значит мы можем анализировать данные вместе, без обязательного деления по тарифам.<br>
___Гипотезу о том, что  средняя выручка по тарифам в Москве значимо не отличается от средней выручки по тарифам в Других городах опровергнуть не смогли.___<br>
Возможно выручка отличается и результат может быть связан с недостаточной выборкой или  средняя выручка значимо не отличается. Точно сказать не возможно.

<div class="alert alert-warning">
<h2> Комментарий наставника</h2>

В случае, когда на одних и тех же данных тестируется несколько гипотез (проводится несколько тестов), всегда нужно проводить коррекцию уровня значимости. Один из вариантов это сделать - поправка Бонферрони. Можешь почитать про нее. Это связано с тем, что чем больше ты пытаешься найти значимый эффект, тем больше вероятность его обнаружить просто по чистой случайности. 

</div>

### Какой тариф приносит больше денег?

Главный вопрос исследования выяснить какой из тарифов приносит больше денег.<br>
Для этого мы сложим Arpu и посмотрим.

In [ ]:
ar_table = pd.DataFrame()

for k in df_users_join['tariff'].unique():
        ar_table.loc[k,'arpu_sum'] = df_users_join[df_users_join[
            'tariff'] == k]['arpu'].sum() 
        ar_table.loc[k,'arpu_sum_ratio'] = df_users_join[df_users_join[
            'tariff'] == k]['arpu'].sum() / df_users_join['arpu'].sum()   
print(bold(),colored("Какой тариф приносит больше денег?",'blue'), bold_end())
print(ar_table)
print("\n")

#### Вывод

Больше денег в целом приносят пользователи тарифа smart

<div class="alert alert-success">
<h2> Комментарий наставника</h2>

В сумме Смарт приносит больше выручки. Однако в среднем на одного клиента Ультра почти в 2 раза выгоднее для компании. 

</div>

### Шаг 5. Напишите общий вывод

In [3]:
#Код для подготовки граффиков в выводы
#город
df_users_join['city_type'] = df_users_join['city'].where(((df_users_join[
    'city'] == 'Санкт-Петербург') | (df_users_join['city'] == 'Москва')), 'Другой город')

def where_city():
    i_table = pd.DataFrame()
    for k in df_users_join['city_type'].unique():
        i_table.loc[k,'ratio'] = df_users_join[df_users_join['city_type'] == k][
            'city_type'].count() / df_users_join['city_type'].count()
    i_table.plot(y = "ratio", kind = "pie")
    plt.title("Откуда пользователи?", fontsize=15)
    plt.xlabel(" ")
    plt.ylabel(" ")
    x1 = i_table.loc[['Другой город'],['ratio']].values
    x2 = i_table.loc[['Москва'],['ratio']].values
    x3 = i_table.loc[['Санкт-Петербург'],['ratio']].values
    plt.text(-0.5,0.2, (str(int(np.round(x1*100,0)))+"%"), fontdict={'size':16}, color='white')
    plt.text(0.15,-0.6, (str(int(np.round(x2*100,0)))+"%"), fontdict={'size':16}, color='white')
    plt.text(0.5,-0.2, (str(int(np.round(x3*100,0)))+"%"), fontdict={'size':16}, color='white')
    plt.legend('')
    plt.show()

NameError: name 'df_users_join' is not defined

In [ ]:
# Сгруппирую переменную age_group
def age_group(row):
        age = row['age']
        if age < 26 and age >= 17:
            return '18 -  26 лет'
        if age < 36 and age >= 26:
            return '26 - 35 лет'
        if age < 46 and age >= 36:
            return '36 - 46 лет'
        if age < 56 and age >= 46:
            return '46 - 56 лет'
        if age < 66 and age >= 56:
            return '56 - 66 лет'
        if age < 76 and age >= 66:
            return '66 - 76 лет'
        if age >= 76 :
            return 'Более 75 лет'
        else:
            return 'Ошибка'

df_users_join['age_group'] = df_users_join.apply(age_group, axis=1)
pivot = df_users_join.pivot_table(index=['age_group'], values='total', aggfunc='count')
pivot = pivot.reset_index()

pivot['total'] = pivot['total']/500

def what_age():
    pivot.plot(x='age_group', y= 'total',  kind = 'bar' , color =  "y" , alpha=0.5,)
    plt.title("Возрастные группы", fontsize=15)
    plt.xlabel(" ")
    plt.ylabel(" ")
    x1 = pivot.loc[2:2,['total']].values
    x2 = pivot.loc[0:0,['total']].values
    plt.text(-0.25,0.14, (str(int(np.round(x2*100,0)))+"%"), fontdict={'size':16}, color='red')
    plt.text(1.71,0.21, (str(int(np.round(x1*100,0)))+"%"), fontdict={'size':16}, color='green')
    plt.legend('')
    plt.ylim((min(pivot['total']) - (np.std(pivot['total'])*2 )), 
             (max(pivot['total']) + (np.std(pivot['total'])*2 )))
    plt.show()

In [ ]:
#тарифы в долях
def what_tariff():
    i_table = pd.DataFrame()
    for k in df_users_join['tariff'].unique():
        i_table.loc[k,'ratio'] = df_users_join[df_users_join['tariff'] == k][
            'tariff'].count() / df_users_join['tariff'].count()
    i_table.plot(y = "ratio", kind = "pie")
    x1 = i_table.loc[['smart'],['ratio']].values
    x2 = i_table.loc[['ultra'],['ratio']].values
    plt.title("Каким тарифом больше пользуются? ", fontsize=15)
    plt.xlabel(" ")
    plt.ylabel(" ")
    plt.text(0.2,0.4, (str(int(np.round(x2*100,0)))+"%"), fontdict={'size':16}, color='white')
    plt.text(-0.5,-0.4, (str(int(np.round(x1*100,0)))+"%"), fontdict={'size':16}, color='white')
    plt.legend('')
    plt.show()

In [ ]:
def mean_round():
    i_table = pd.DataFrame()
    for i in ["calls_min","session_mb","message_count"]:
        for k in df_users_join['tariff'].unique():
            i_table.loc[i,k] = round(df_users_join[df_users_join['tariff'] == k][i].mean(),-1)
    print(bold(), "Необходимое количество для клиентов \n (Среднее значение)", bold_end())
    print(i_table)

In [ ]:
#Хватает ли услуг
def enough():
    k_table = pd.DataFrame()
    for k in df_users_join['tariff'].unique():
        k_table.loc["minutes",k] =   round(df_users_join[df_users_join['tariff'] == k][
            'calls_min'].mean(),-1) / df_users_join[df_users_join['tariff'] == k][
            'minutes_included'].mean()
        k_table.loc["megabytes",k] =  round(df_users_join[df_users_join['tariff'] == k][
            'session_mb'].mean(),-1) / df_users_join[df_users_join['tariff'] == k][
            'mb_per_month_included'].mean() 
        k_table.loc["messages",k] = round(df_users_join[df_users_join['tariff'] == k][
            'message_count'].mean(),-1) / df_users_join[df_users_join['tariff'] == k][
            'messages_included'].mean()  
    print(bold(), "Доля использованных услуг относительно обьема услуг, входящих в АП\n Лишние/Недостающие услуги", bold_end())
    sns.heatmap(k_table, xticklabels=k_table.columns, yticklabels=k_table.index,
                center=0, annot=True, vmin=0, vmax=1.2 )
    plt.show()

In [ ]:
#табличка о плате тарифа

def pay():
    z_table = pd.DataFrame()
    r_table = pd.DataFrame()
    for i in ["rub_monthly_fee", 'arpu']:
        for k in df_users_join['tariff'].unique():
            z_table.loc[i,k] = df_users_join[df_users_join['tariff'] == k][i].mean()
    for k in df_users_join['tariff'].unique():
        r_table.loc['ratio',k] = df_users_join[df_users_join['tariff'] == k][
            'arpu'].mean() / df_users_join[df_users_join['tariff'] == k]['rub_monthly_fee'].mean()
    print(bold(),"Оплата тарифа", bold_end())
    print(z_table)
    sns.heatmap(r_table, xticklabels=r_table.columns, yticklabels=r_table.index,
            center=0, annot=True, vmin=1, vmax=3 )
    plt.show()
    

In [ ]:
#количество денег
def more_money():
    ar_table.plot(y = "arpu_sum_ratio", kind = "pie")
    x1 = ar_table.loc[['smart'],['arpu_sum_ratio']].values
    x2 = ar_table.loc[['ultra'],['arpu_sum_ratio']].values
    plt.title("Какой тариф приносит больше денег? ", fontsize=15)
    plt.xlabel(" ")
    plt.ylabel(" ")
    plt.text(0.2,0.4, (str(int(np.round(x2*100,0)))+"%"), fontdict={'size':16}, color='white')
    plt.text(-0.5,-0.4, (str(int(np.round(x1*100,0)))+"%"), fontdict={'size':16}, color='white')
    plt.legend('')
    plt.show()

## Вывод

## Что поменяли или добавили в базу ? 

* В базах звонков и соединений с интернетом в переменных обозначающих количество минут и МБ удалили нулевые значения.
* При подсчете в тарифе идет округление вверх до минут и МБ соответственно. Округлили в базах аналогично.

### В базу клиентов добавлены новые переменные:

* Информация о месяце подключения и отключения от тарифа - *reg_month, churn_month*
<br>

* Информация о тарифах - *messages_included, mb_per_month_included, minutes_included, rub_monthly_fee, rub_per_gb, rub_per_message, rub_per_minute*
<br>

* Количество сделанных звонков по месяцам - *calls_count_month_1-12* 
* Количество израсходованных минут разговора по месяцам - *calls_min_month_1-12* 
* Количество отправленных сообщений по месяцам - *message_count_month_1-12* 
* Объем израсходованного интернет-трафика по месяцам - *session_mb_month_1-12* 
* Помесячную выручку с каждого пользователя. Рассчитали (с учетом, что что не все клиенты были подключены к тарифу в течении всего года). - *arpu_month_1-12* 


__Также данные показатели рассчитаны средний показатель по месяцам, за в те месяцы, когда клиент был подключен к тарифу__ * (calls_min,calls_count,session_mb, message_count, arpu)*

###  Поведение клиентов оператора

In [ ]:
where_city()

* 1 из 5 клиентов из Москвы
* 1 из 10 - из Санкт-Петербурга

In [ ]:
what_age()

___В базе представлены клиенты от 18 до 75 лет.___
* Наиболее наполнена группа - 36 - 46 лет
* Наименее - молодеж (до 26 лет)

In [ ]:
what_tariff()

* Две трети пользователей подключены к тарифу smart
* Только одна треть к тарифу ultra

###  Как используют?

In [ ]:
print(bold(),colored("Справочная информация по тарифам",'green'), bold_end())
info_table

In [ ]:
mean_round()

__Тариф ultra__
* Клиенты в среднем используют до 520 минут разговора в месяц 
* Около 2 ГБ интернет-трафика
* Отсылают около 50 сообщений в месяц

__Тариф  smart__
* Клиенты в среднем используют до 420 минут разговора в месяц 
* Около 1.6 ГБ интернета
* Отсылают около 30 сообщений в месяц

__Пользователи тарифа Ultra больше разговаривают по телефону, чем клиенты Smart. В среднем на 100 минут.__
__Клиенты Ultra используют интернет более активно.(+ 0,3 ГБ)__<br>
__Сообщения наименее популярная услуга. В среднем клиенты Ultra больше посылают сообщений (на 20 штук).__

### Хватает ли клиентам ?

In [ ]:
enough()

* Клиенты ultra используют менее 20% от объема включенных минут и сообщений. 
* Клиенты smart используют практически весь запас минут для разговора и более половины обьема сообщений.
Обычно клиенты выходят за рамки Гб включенных в АП.


__Наиболее активно на обоих тарифах используют пакеты  интернета.__<br>
Вероятно, обьем интернета - одна из наиболее важных критериев при принятии решения о тарифе.<br>
__В рекламном сообщении рекомендуется сделать акцент на обьем интернет пакетов включенных в тариф.__

### ARPU и Какой тариф приносит больше денег?

In [ ]:
pay()

__Пользователи тарифа Ultra больше платят в месяц, чем клиенты Smart. Это обоснованно в первую очередь различным минимумом оплаты в месяц - абонентской платой.__
* Пользователи тарифа Ultra в подавляющем случае не платят сверх АП. Переплаты скорее всего связанны с закупкой ГБ сверх тарифа.

* Среднее arpu клиентов Smart сильно выше АП в 550 рублей. В среднем они платят в 2.4 раза больше АП. 

In [ ]:
more_money()

____Пользователи тарифа smart приносят больше прибыли, чем пользователи тарифа ultra____

При этом необходимо учитывать, что в среднем пользователь smart приносит значимо меньшую больше, чем пользователь ultra. <br>
И разница в выручке связанна с тем, что большинство (70%) пользователей подключены к "более дешевому" тарифу smart.


 <div class="alert alert-success">
<h2> Комментарий наставника</h2>

Выводы описаны грамотно, а сделаны довольно нетривиально. Приведены ответы на главные вопросы проекта. В выводах можно приводить полученные ранее значения. Здорово, что по каждому пункту работы дан комментарий. Еще лучше будет, если приведешь рекомендации для компании по дальнейшим действиям. 

</div>

<div class="alert alert-success">
<h2> Комментарий наставника</h2>

Если тебе нравится тема визуализации, то можешь изучить методы библиотеки plotly. Она позволяет строить довольно презентабельные графики. Ссылку на один из графиков привел в работе. 

Ты проделала большую работу, молодец! Критических замечаний нет. Одним из самых значимых желтых комментариев является комментарий про изменение структуры таблицы. При наличии времени просто попробуй ее реализовать и пойми, чем она будет отличаться от используемой тобой структуры. Переделывать не заставляю, т.к. ошибок твой способ не вызвал, однако иная структра таблицы позволит использовать меньше кода, а значит больше сосредоточиться на самих данных и выводах. В остальном работа сделана здорово. По каждому пункту есть комментарии. Продолжай в том же духе :)

</div>